#pragma once
#include<vector.h>
#include <stdio.h>
#include <stdlib.h>
#include <time.h>


static char* builders[] = {
    "OOO Promzona", "Deltaplan", "Build Gods", "Spring_Wild",
    "Build Bad", "Peab", "NCC", "Skanska", "Veidekke Sverige",
    "JM", "Svevia", "AF Gruppen", "R?nesans Holding", "Limak Holding",
    "Tekfen Construction & Installation", "Merkezi", "TAV",
    "Construction ENKA", "Mapa Group", "Sinpas GYOIC Holding",
    "Saipem Webuild", "Maire Tecnimont", "Bonatti", "ASTM",
    "SICIM", "Impresa Pizzarotti & C.", "3CHD", "Aquatechnic S.A.",
    "ASV Montage", "Arendt S.A.", "ArcelorMittal Construction",
    "Baatz Constructions Exploitation", "Balthasar Constructions",
    "YTL Corporation Berhad", "Sunway Group", "UEM Group Berhad", "Muhibbah Engineering",
    "WCT Holdings Berhad", "IJM Corporation", "VanWonen Investeringsmaatschappij",
    "Easy Housing Concepts", "Atlas Copco International", "Orion-Staete",
    "Xinaps", "Connec2", "Koninklijke BAM Groep", "Arabtec Construction L.L.C.",
    "Al Jaber LEGT Engineering & Contracting", "Al Habtoor Group", "Al Futtaim", "Al Naboodah Construction Company",
    "Fuja", "National Construction Co. L.L.C.", "Arabian Construction Company", "Bechtel Group Inc.",
    "Fluor Corporation", "Skanska Group", "Turner Construction", "Kiewit Corp.", "STO Building Group Inc.",
    "Black & Veatch", "Nesma & Partners", "AlBawani", "El Seif Engineering Contracting", "Almabani", "IHCC",
    "Shahm Contracting Company", "Construction and Planning Co.", "PCL Construction", "Ashoka Buildcon",
    "Aarsleff Holding", "Ramboll", "Saint-Gobain", "MT H?jgaard Holding", "Hilti Group", "HusCompagniet", "SEC",
    "Keo Construction", "Consolidated Contractors Company", "Farab", "Mapna Group", "Kayson Group", "Tekfen Construction", "Monenco",
    "China State Construction Engineering Corp.", "China Railway Group Ltd.", "Power Construction Corp. of China",
    "Samsung C&T Corporation", "Hyundai Engineering & Construction", "Daewoo Engineering & Construction",
    "Obayashi Corporation", "Kajima Corporation", "Shimizu Corporation", "Taisei Corporation",
    "Larsen & Toubro", "Shapoorji Pallonji Group", "DLF Limited", "Godrej Properties",
    "Brigade Enterprises", "Sobha Ltd.", "Prestige Group", "Mahindra Lifespaces",
    "Bouygues Construction", "Vinci Construction", "Eiffage Construction", "Spie Batignolles",
    "Strabag SE", "Bilfinger SE", "Hochtief AG", "Z?blin International",
    "Ferrovial Construction", "ACS Group", "OHLA", "Sacyr",
    "Cimolai S.p.A.", "Astaldi S.p.A.", "Webuild S.p.A.", "Salini Impregilo",
    "Colas Group", "Fayat Group", "Egis Group", "Soletanche Bachy",
    "Royal BAM Group", "VolkerWessels", "Heijmans", "Ballast Nedam",
    "Skanska UK", "Balfour Beatty", "Morgan Sindall", "Kier Group",
    "Laing O'Rourke", "Galliford Try", "McLaren Construction", "Wates Group",
    "Multiplex Construction", "Lendlease Corporation", "CIMIC Group",
    "AECOM", "Jacobs Engineering Group", "WSP Global", "Tetra Tech",
    "Dragados USA", "Flatiron Construction", "Walsh Group", "Clark Construction",
    "Hensel Phelps", "Gilbane Building Co.", "Whiting-Turner", "Barton Malow",
    "DPR Construction", "Sundt Construction", "Mortenson Construction", "JE Dunn Construction",
    "Skanska USA", "Turner Industries", "Fluor Daniel", "Bechtel Infrastructure",
    "Granite Construction", "Keller Group", "Bauer AG", "Soletanche Freyssinet",
    "Mott MacDonald", "Arup Group", "AtkinsR?alis", "TYLin Group",
    "Gazprombank Development", "PIK Group", "GK LSR", "Etalon Group",
    "SU-155", "Donstroy", "MR Group", "Capital Group",
    "Samolyot", "A101", "GK Fortum", "GK Normann",
    "Renaissance Development", "Ingrad", "GK Stroyinvest", "GK Stroymontazh",
    "Glavstroy", "Transinzhstroi", "Mosinzhproekt", "Metrostroy",
    "Roszheldorstroy", "Spetsmost", "Mostotrest", "Avtodorstroy",
    "Zheldorstroy", "Transstroy", "Gidrospetsstroy", "Atomstroyexport",
    "Rosatom Construction", "T Plus Engineering", "Rosseti Engineering",
    "Gazprom Transgaz", "Transneft Diascan", "Rosneft Engineering",
    "OOO Stroygrad", "OOO DomStroy", "OOO Novy Krai", "OOO Granit Plus",
    "OOO StroyInvest", "OOO Metropolis Development", "OOO UralStroy", "OOO VolgaBuild",
    "OOO SiberStroy", "OOO Baikal Engineering", "OOO FarEast Constructors",
    "OOO Northern Lights Construction", "OOO Southern Cross Builders",
    "OOO Horizon Group", "OOO VectorBuild", "OOO TerraFirma",
    "OOO Skyline Developers", "OOO UrbanCore", "OOO EcoHabitat",
    "OOO GreenFrame", "OOO SmartBuild Solutions", "OOO NextGen Construction",
    "OOO Legacy Builders", "OOO Heritage Construction", "OOO Pioneer Group",
    "OOO Apex Engineering", "OOO Vertex Construction", "OOO Summit Build",
    "OOO Horizon Constructors", "OOO IronRoot", "OOO StoneBridge",
    "OOO TimberFrame", "OOO SteelHaven", "OOO ConcreteCraft",
    "OOO Mason & Co.", "OOO Wright & Partners", "OOO Langdon & Fry",
    "OOO Hudson Construction", "OOO Thames Builders", "OOO Clyde Engineering",
    "OOO Rhine Group", "OOO Seine Developments", "OOO Danube Constructors",
    "OOO Alps Construction", "OOO Pyrenees Build", "OOO Carpathian Engineering",
    "OOO Baltic Shore Builders", "OOO Adriatic Coast Development",
    "OOO Pacific Rim Constructors", "OOO Gulf Horizon", "OOO Desert Bloom",
    "OOO Oasis Group", "OOO Prairie Builders", "OOO Evergreen Construction",
    "OOO Cedar & Oak", "OOO Maple Ridge", "OOO Willow Creek",
    "OOO Riverstone", "OOO Mountain View", "OOO Lakeside Homes",
    "OOO Harbor Town", "OOO Meadow Lane", "OOO Sunnyside Estates",
    "OOO Moonlight Developments", "OOO Starlight Builders", "OOO Dawn Construction",
    "OOO Twilight Group", "OOO Horizon Point", "OOO Vista Heights",
    "OOO Summit Ridge", "OOO RidgeLine", "OOO Cliffside",
    "OOO Valley Forge", "OOO Oakwood", "OOO Pinecrest",
    "OOO Brookside", "OOO Hillcrest", "OOO Westfield",
    "OOO Eastgate", "OOO Northpoint", "OOO Southshore"
};
static char* districts[] = {
    "Altushkovo", "Odinsovo", "Rumanovo", "Konevo",
    "Kluevo", "Orehovo", "Vodovo", "Zorino", "Voshodovo", "Shahtinskiy",
    "Dedkovo", "Dushkiy", "Berezni", "Sosnovo", "Lugino", "Borisovo",
    "Gribovo", "Kolychevo", "Malinovka", "Osinovo", "Petrovskoe", "Rastunovo",
    "Seleznevo", "Tarasovka", "Ushakovo", "Fedotovo", "Khavrino", "Golygiino",
    "Zhelezino", "Ivankovo", "Kalinino", "Lobnino", "Mayskoe", "Novoselo",
    "Oktyabrskoye", "Pirogovo", "Raevka", "Solnechnoye", "Troitskoye", "Ustye",
    "Fominskoe", "Kamenka", "Lebedevo", "Morozovo", "Nikolskoe", "Ozernoe",
    "Pervovka", "Raduzhnoe", "Svetloye", "Trudovaya", "Ushakovo-2", "Filatovka",
    "Gorki", "Zaruchyevo", "Ivanovka", "Kalinovka", "Lipki", "Mogilino",
    "Novinki", "Orlovo", "Peski", "Rodniki", "Samarino", "Tishino", "Uralskoe",
    "Vyborgskoe", "Yaropolchino", "Zavetnoe", "Abramovo", "Bryanskoye", "Veselino",
    "Grinyovo", "Dubrovka", "Ezhevo", "Zharino", "Zvenigorodskoe", "Klyuchi",
    "Lozhi", "Merenki", "Narskoe", "Obrosovo", "Prudy", "Rasskazovo", "Slavnoe",
    "Terebino", "Ushachy", "Fedorovskoe", "Guslitsy", "Zaborye", "Kashinovo",
    "Acton", "Beckenham", "Belgravia", "Bethnal Green",
    "Brentford", "Camberwell", "Carshalton", "Chadwell Heath",
    "Chingford", "Clapham", "Crystal Palace", "Dalston",
    "Dulwich", "East Ham", "Edgware", "Elephant And Castle",
    "Eltham", "Epping", "Erith", "Finsbury Park",
    "Forest Hill", "Fulham", "Golders Green", "Greenwich",
    "Hackney", "Hampton", "Hampstead", "Harlesden",
    "Harrow", "Hendon", "Herne Hill", "Highgate",
    "Hillingdon", "Holloway", "Hounslow", "Ilford",
    "Islington", "Kennington", "Kensington", "Kilburn",
    "Kingston", "Lambeth", "Lewisham", "Limehouse",
    "Maida Vale", "Manor House", "Marylebone", "Mitcham",
    "Muswell Hill", "New Cross", "Newham", "Norwood",
    "Notting Hill", "Peckham", "Penge", "Pimlico",
    "Pinner", "Plaistow", "Poplar", "Putney",
    "Richmond", "Rotherhithe", "Seven Sisters", "Shepherd's Bush",
    "Shoreditch", "Sidcup", "Soho", "Southall",
    "Streatham", "Sutton", "Teddington", "Tooting",
    "Twickenham", "Uxbridge", "Vauxhall", "Walthamstow",
    "Walworth", "Wanstead", "Wembley", "Wimbledon",
    "Wood Green", "Woolwich", "York Road", "Bromley-By-Bow"
};


vector* generate(u_int num);
